name: tch-tex
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - invoke=1.1.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.0.2p
  - pip=10.0.1
  - python=3.7.0
  - readline=7.0
  - setuptools=40.2.0
  - sqlite=3.24.0
  - tk=8.6.8
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - jinja2==2.10
    - markdown==2.6.11
    - markupsafe==1.0
prefix: /home/vince/anaconda3/envs/tch-tex

